services:
  addok:
    image: pack-solutions/addok:1.2.0
    ports:
    - "7878:7878"
    volumes:
    - ./addok-data/addok.conf:/etc/addok/addok.conf
    - ./addok-data/addok.db:/data/addok.db
    - ./logs:/logs
    links:
    - addok-redis:redis
    environment:
      - WORKERS=1
      - WORKER_TIMEOUT=30
      - LOG_QUERIES=1
      - LOG_NOT_FOUND=1
      - SLOW_QUERIES=200
      - DD_AGENT_HOST=datadog
      - DD_SERVICE=addok
      - DD_ENV=dev
      - DD_VERSION=1.2.0
  addok-redis:
    image: etalab/addok-redis
    volumes:
      - ./addok-data/dump.rdb:/data/dump.rdb
  datadog:
    container_name: dd-agent
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_ENV=local
      - DD_SITE=datadoghq.eu
      - DD_APM_ENABLED=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
      - DD_APM_FILTER_TAGS_REJECT="service:datadog-agent"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

